version: '3.8'

services:
  # PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-aggregator
    image: news-aggregator
    ports:
      - "9000:9000"  # Expose port 9000 for PHP-FPM
    volumes:
      - .:/var/www  # Mount current directory into the container
    networks:
      - laravel

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8080:80"  # Expose port 8080 for the Nginx server
    volumes:
      - .:/var/www  # Mount current directory into the container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx configuration
    depends_on:
      - app
    networks:
      - laravel

  # MySQL service
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  # Composer service for running composer commands
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data:
    driver: local
